import logoAnsell from "../assets/img/logos/ANN.AX_BIG.png";
import msaSafety from "../assets/img/logos/msa-safety-logo-vector.png";
import tresM from "../assets/img/logos/pngwing.com.png";
import honeywell from "../assets/img/logos/pngegg.png";
import clute from "../assets/img/logos/Clute-logo.png";
import dragger from "../assets/img/logos/draeger-vector-logo.svg";
import uvex from "../assets/img/logos/uvex-seeklogo.com.svg";
import showa from "../assets/img/logos/Showa-Logo-300x134.png";
import outpont from "../assets/img/logos/outpont.png";
import howard from "../assets/img/logos/howardleightlogo.jpg";
import libus from "../assets/img/logos/logo-libus.png";
export const LOGOANSELL = logoAnsell;
export const MSASAFETY = msaSafety;
export const TRESM = tresM;
export const HONEYLWELL = honeywell;
export const CLUTE = clute;
export const DRAGGER = dragger;
export const UVEX = uvex;
export const SHOWA = showa;
export const OUTPONT = outpont;
export const HOWARD = howard;
export const LIBUS = libus;
